version: "3.9"

services:
  emby-dedup:
    build: .
    container_name: emby-dedup
    ports:
      - "5055:5055"
    volumes:
      - ./config:/config
    environment:
      - APP_DB_PATH=/config/app.db
      - APP_CONFIG_PATH=/config/config.json
      - APP_LOGS_DIR=/config/logs
    restart: unless-stopped
